### ISSUE TITLE
Clicking "Initialize" twice results in an uncaught TypeError

### ISSUE THREAD

**Issue by mariofink** [rolodato/volca-keys-editor#7]
When you click on the "Initialize" button (next to the channel and device drop-downs) multiple times triggers JavaScript errors. The first click is okay, but on the second you start getting these kind of errors:

`Uncaught TypeError: Cannot read property 'initialize' of null
    at midiParams.forEach.param (https://volcaeditor.com/dist/bundle.js:21584:48)
    at Array.forEach (native)
    at MidiDevice.initialize (https://volcaeditor.com/dist/bundle.js:21584:26)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://volcaeditor.com/dist/bundle.js:6432:17)
    at executeDispatch (https://volcaeditor.com/dist/bundle.js:6216:22)
    at Object.executeDispatchesInOrder (https://volcaeditor.com/dist/bundle.js:6239:6)
    at executeDispatchesAndRelease (https://volcaeditor.com/dist/bundle.js:5661:23)
    at executeDispatchesAndReleaseTopLevel (https://volcaeditor.com/dist/bundle.js:5672:11)
    at Array.forEach (native)
    at forEachAccumulated (https://volcaeditor.com/dist/bundle.js:6533:10)`

**Comment by rolodato** [comment]
Confirmed, thanks for reporting! It will be a while before I can get to fixing this, though. PRs are always welcome :)
